In [103]:

# Obter o dataset
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix

df = pd.DataFrame(pd.read_pickle('../wifi_dict.pkl'))
X = df[df.columns.difference(['COMODO'])].values.astype(int)
Y = df['COMODO'].values 

In [142]:
def show_results(n_neighbors, s_accuracy, s_precision, s_recall, f1, conf_matrix):
    print("n_neighbors: {ngh}".format(ngh=n_neighbors))
    print("precision_score {pre}: ".format(pre=s_precision))
    print("recall_score: {re} ".format(re=s_recall))
    print("f1_score: {f1}".format(f1=f1) )
    print("accuracy_score {acc}".format(acc=s_accuracy))
    print("confusion_matrix:\n {conf}".format(conf=conf_matrix))

In [126]:
def get_metrics(k_neighbor, accuracy_list,y_test,y_predicted):
    s_accuracy = accuracy_score(y_test, y_predicted)
    accuracy_list.append(s_accuracy)
    mean = np.mean(accuracy_list)
    std = np.std(accuracy_list)
    conf_matrix = confusion_matrix(y_test, y_predicted)
    s_recall = recall_score(y_test,y_predicted, average='micro')
    s_precision = precision_score(y_test, y_predicted, average='micro')
    s_f1 = f1_score(y_true=y_test, y_pred=y_predicted, average='micro')
    show_results(i, s_accuracy, s_precision, s_recall, s_f1, conf_matrix)
    return  (k_neighbor, std, mean, s_f1)

In [139]:
sss = StratifiedShuffleSplit(n_splits=10, test_size=0.3, train_size=0.7,random_state=9)
best_neighbors = {}
for i in range(1,13):
    knn = KNeighborsClassifier(n_neighbors = i)
    x_normalized = (X - X.mean(axis=0)) / X.std(axis=0)
    accuracy_list = []

    for _, test_index in sss.split(x_normalized,Y):
        x_test, x_validation, y_test, y_validation = train_test_split(x_normalized[test_index],
                                                                                    Y[test_index],
                                                                                    test_size=0.5,
                                                                                    random_state=0)

        knn.fit(x_validation, y_validation)
        y_predicted = knn.predict(x_test)
        __, std, mean, s_f1 = get_metrics(i, accuracy_list, y_test, y_predicted)
        best_neighbors[s_f1] = (i, std, mean)

best_neighbor = best_neighbors[max(best_neighbors)]

n_neighbors: 1
precision_score 0.5: 
recall_score: 0.5 
f1_score: 0.5
accuracy_score 0.5
confusion_matrix [[1 0 0 0]
 [0 2 0 0]
 [1 4 0 1]
 [0 0 0 3]]
n_neighbors: 1
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix [[3 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 3]]
n_neighbors: 1
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix [[2 0 0 0]
 [0 5 0 0]
 [0 0 2 0]
 [0 0 0 3]]
n_neighbors: 1
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix [[4 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 5]]
n_neighbors: 1
precision_score 0.9166666666666666: 
recall_score: 0.9166666666666666 
f1_score: 0.9166666666666666
accuracy_score 0.9166666666666666
confusion_matrix [[4 0 0 0]
 [1 1 0 0]
 [0 0 3 0]
 [0 0 0 3]]
n_neighbors: 1
precision_score 0.8333333333333334: 
recall_score: 0.8333333333333334 
f1_score: 0.8333333333333334
accuracy_score 0.8333333333333334
confusion_matrix [[3 0 0 0]
 [0 1 0 

In [143]:
k_neighbor = best_neighbor[0]
knn = KNeighborsClassifier(n_neighbors=k_neighbor)
x_normalized = (X - X.mean(axis=0)) / X.std(axis=0)
accuracy_list = list()

for train_index, test_index in sss.split(x_normalized, Y):
    x_test  = x_normalized[test_index]
    y_test  = Y[test_index]
    knn.fit(x_normalized[train_index], Y[train_index])
    y_predicted = knn.predict(x_test)
    get_metrics(k_neighbor, accuracy_list, y_test, y_predicted)

std = np.std(accuracy_list)
mean = np.mean(accuracy_list)
print(f"Média: %4.3f Std: %4.3f para {best_neighbor[0]} vizinhos "%(mean, std))

n_neighbors: 12
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix:
 [[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 6]]
n_neighbors: 12
precision_score 0.9583333333333334: 
recall_score: 0.9583333333333334 
f1_score: 0.9583333333333334
accuracy_score 0.9583333333333334
confusion_matrix:
 [[6 0 0 0]
 [1 5 0 0]
 [0 0 6 0]
 [0 0 0 6]]
n_neighbors: 12
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix:
 [[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 6]]
n_neighbors: 12
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix:
 [[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 6]]
n_neighbors: 12
precision_score 0.9583333333333334: 
recall_score: 0.9583333333333334 
f1_score: 0.9583333333333334
accuracy_score 0.9583333333333334
confusion_matrix:
 [[6 0 0 0]
 [1 5 0 0]
 [0 0 6 0]
 [0 0 0 6]]
n_neighbors: 12
precision_score 1.0: 
recall_score: 1.0 
f1_score: 1.0
accuracy_score 1.0
confusion_matrix:
 [